module.exports = {
  watak: function watak(angka) {
    var w;
    if (angka == 0) {
      w = [
        "byoma",
        "musna",
        "nis",
        "mlethik",
        "langit",
        "sirna",
        "ilang",
        "kombul",
        "awang-awang",
        "mesat",
        "muluk",
        "gegana",
        "nglès",
        "tumenga",
        "nenga",
        "luhur",
        "suwung",
        "sonya",
        "muksa",
        "doh",
        "tebih",
        "swarga",
        "tanpa",
        "barakan",
        "tan",
        "rusak",
        "brastha",
        "swuh",
        "walang",
        "kos",
        "pejah",
        "akasa",
        "tawang",
        "wiyat",
        "oncat",
        "windu",
        "widik-widik",
        "nir",
        "wuk",
        "sat",
        "surud",
        "sempal",
      ];
    } else if (angka == 1) {
      w = [
        "tunggal",
        "gusti",
        "sujanma",
        "semedi",
        "badan",
        "nabi",
        "rupa",
        "maha",
        "buddha",
        "niyata",
        "luwih",
        "pamasé",
        "wong",
        "buweng",
        "rat",
        "lèk",
        "iku",
        "surya",
        "candra",
        "kartika",
        "bumi",
        "wiji",
        "urip",
        "ron",
        "éka",
        "prabu",
        "kenya",
        "nekung",
        "raja",
        "putra",
        "sasa",
        "dhara",
        "peksi",
        "dara",
        "tyas",
        "wungkul",
        "sudira",
        "budi",
        "wani",
        "hyang",
        "jagad",
        "nata",
      ];
    } else if (angka == 2) {
      w = [
        "asta",
        "kalih",
        "ro",
        "nembah",
        "ngabekti",
        "nétra",
        "kembar",
        "myat",
        "mandeng",
        "nayana",
        "swiwi",
        "lar",
        "sikara",
        "gandhèng",
        "paksa",
        "apasang",
        "sungu",
        "athi-athi",
        "talingan",
        "dresthi",
        "carana",
        "tangan",
        "karna",
        "bau",
        "suku",
        "caksuh",
        "mata",
        "paningal",
        "locana",
        "ama",
        "nebah",
        "karnan",
        "ngrengga",
        "pengantèn",
        "dwi",
        "kanthi",
        "buja",
        "bujana",
      ];
    } else if (angka == 3) {
      w = [
        "bahni",
        "tiga",
        "ujwala",
        "kaèksi",
        "katon",
        "murub",
        "dahana",
        "payudah",
        "katingalan",
        "kaya",
        "bentèr",
        "nala",
        "uninga",
        "kawruh",
        "lir",
        "wrin",
        "wéda",
        "naut",
        "nauti",
        "teken",
        "siking",
        "pawaka",
        "kukus",
        "api",
        "apyu",
        "brama",
        "rana",
        "rananggana",
        "utawaka",
        "uta",
        "ujel",
        "kobar",
        "agni",
        "wignya",
        "guna",
        "tri",
        "jatha",
      ];
    } else if (angka == 4) {
      w = [
        "catur",
        "warna",
        "wahana",
        "pat",
        "warih",
        "waudadi",
        "dadya",
        "keblat",
        "papat",
        "toya",
        "suci",
        "udaka",
        "we",
        "woh",
        "nadi",
        "jladri",
        "sindu",
        "yoga",
        "gawé",
        "tlaga",
        "hèr",
        "wening",
        "udan",
        "bun",
        "tirta",
        "marta",
        "karya",
        "sumber",
        "sumur",
        "masuh",
        "marna",
        "karti",
        "karta",
        "jalaniddhi",
        "samodra",
        "udaya",
        "tasik",
        "tawa",
        "segara",
        "wédang",
      ];
    } else if (angka == 5) {
      w = [
        "pandhawa",
        "lima",
        "wisikan",
        "gati",
        "indri",
        "indriya",
        "warastra",
        "wrayang",
        "astra",
        "lungid",
        "sara",
        "saré",
        "guling",
        "raseksa",
        "diyu",
        "buta",
        "galak",
        "wil",
        "yaksa",
        "yaksi",
        "saya",
        "wisaya",
        "bana",
        "jemparing",
        "cakra",
        "hru",
        "tata",
        "hanata",
        "bayu",
        "bajra",
        "samirana",
        "pawaka",
        "maruta",
        "angin",
        "panca",
        "marga",
        "margana",
      ];
    } else if (angka == 6) {
      w = [
        "rasa",
        "nenem",
        "rinaras",
        "artati",
        "lona",
        "tikta",
        "madura",
        "sarkara",
        "amla",
        "kayasa",
        "karaséng",
        "oyag",
        "obah",
        "nem",
        "kayu",
        "wreksa",
        "glinggang",
        "prabatang",
        "oyig",
        "sad",
        "anggas",
        "anggang-anggang",
        "mangsa",
        "naya",
        "retu",
        "wayang",
        "winayang",
        "anggana",
        "ilat",
        "kilat",
        "lidhah",
        "lindhu",
        "carem",
        "manis",
        "tahen",
        "osik",
        "karengya",
      ];
    } else if (angka == 7) {
      w = [
        "sapta",
        "prawata",
        "acala",
        "giri",
        "ardi",
        "gora",
        "prabata",
        "himawan",
        "pandhita",
        "pitu",
        "kaswarèng",
        "resi",
        "sogata",
        "wiku",
        "yogi",
        "swara",
        "dwija",
        "suyati",
        "wulang",
        "weling",
        "wasita",
        "tunggang",
        "turangga",
        "gung",
        "swa",
        "aswa",
        "titihan",
        "kuda",
        "ajar",
        "arga",
        "sabda",
        "nabda",
        "angsa",
        "muni",
        "suka",
        "biksu",
        "biskuka",
      ];
    } else if (angka == 8) {
      w = [
        "astha",
        "basu",
        "anggusthi",
        "basuki",
        "slira",
        "murti",
        "bujangga",
        "manggala",
        "taksaka",
        "menyawak",
        "tekèk",
        "dwipa",
        "dwipangga",
        "bajul",
        "gajah",
        "liman",
        "dwirada",
        "èsthi",
        "éstha",
        "matengga",
        "brahma",
        "brahmana",
        "wewolu",
        "baya",
        "bebaya",
        "kunjara",
        "tanu",
        "sarpa",
        "samaja",
        "madya",
        "mangèsthi",
        "panagan",
        "ula",
        "naga",
      ];
    } else if (angka == 9) {
      w = [
        "bolong",
        "nawa",
        "dwara",
        "pintu",
        "kori",
        "bedhah",
        "lawang",
        "wiwara",
        "gapura",
        "rong",
        "song",
        "wilasita",
        "anglèng",
        "trustha",
        "trusthi",
        "trus",
        "butul",
        "déwa",
        "sanga",
        "jawata",
        "manjing",
        "arum",
        "ganda",
        "kusuma",
        "muka",
        "rudra",
        "masuk",
        "rago",
        "angrong",
        "guwa",
        "menga",
        "babahan",
        "lèng",
        "ambuka",
        "gatra",
        "anggangsir",
        "nanda",
        "wangi",
        "wadana",
      ];
    } else {
      w = [];
    }

    return module.exports.choose(w);
  },
  choose: function choose(choices) {
    var index = Math.floor(Math.random() * choices.length);
    return choices[index];
  },
  gen: function gen(angka, t) {
    var hsl, lst;

    lst = function () {
      var _pj_a = [],
        _pj_b = angka.toString();

      for (var _pj_c = 0, _pj_d = _pj_b.length; _pj_c < _pj_d; _pj_c += 1) {
        var a = _pj_b[_pj_c];

        _pj_a.push(a);
      }

      return _pj_a;
    }.call(this);

    lst.reverse();
    hsl = [];

    for (
      var ls, _pj_c = 0, _pj_a = lst, _pj_b = _pj_a.length;
      _pj_c < _pj_b;
      _pj_c += 1
    ) {
      ls = _pj_a[_pj_c];
      hsl.push(module.exports.watak(Number.parseInt(ls)).toString());
    }

    if(t) {
      return hsl.map( a => a.charAt(0).toUpperCase() + a.substr(1) ).join(" ")
    } else {
      return hsl
    }
  },
  getmeaning: function getmeaning(text, i) {
    const obj = require('./data.json');
    if(!obj[text]) {
      return "none"
    } else {
      if(i == "id") {
        if(!obj[text].id) {
          return "none"
        } else {
          return obj[text].id
        }
      } else {
        if(!obj[text].jv) {
          return "none"
        } else {
          return obj[text].jv
        }
      }
    }
  }
};
